
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'FOR IDENTIFIER IF LBRACE LPAREN RBRACE RPAREN SEMICOLON WHILEstatement : IF LPAREN IDENTIFIER RPAREN LBRACE RBRACEstatement : WHILE LPAREN IDENTIFIER RPAREN LBRACE RBRACEstatement : FOR LPAREN IDENTIFIER SEMICOLON IDENTIFIER SEMICOLON IDENTIFIER RPAREN LBRACE RBRACE'
    
_lr_action_items = {'IF':([0,],[2,]),'WHILE':([0,],[3,]),'FOR':([0,],[4,]),'$end':([1,17,18,23,],[0,-1,-2,-3,]),'LPAREN':([2,3,4,],[5,6,7,]),'IDENTIFIER':([5,6,7,13,19,],[8,9,10,16,20,]),'RPAREN':([8,9,20,],[11,12,21,]),'SEMICOLON':([10,16,],[13,19,]),'LBRACE':([11,12,21,],[14,15,22,]),'RBRACE':([14,15,22,],[17,18,23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> IF LPAREN IDENTIFIER RPAREN LBRACE RBRACE','statement',6,'p_statement_if','parser.py',42),
  ('statement -> WHILE LPAREN IDENTIFIER RPAREN LBRACE RBRACE','statement',6,'p_statement_while','parser.py',46),
  ('statement -> FOR LPAREN IDENTIFIER SEMICOLON IDENTIFIER SEMICOLON IDENTIFIER RPAREN LBRACE RBRACE','statement',10,'p_statement_for','parser.py',50),
]
